### ISSUE TITLE
怎么预测呀

### ISSUE THREAD

**Issue by smilelight** [bigboNed3/chinese_text_cnn#1]
首先非常感谢作者您分享的代码，只是如何编写预测代码呢，我这里不是太懂

**Comment by Biaocsu** [comment]
@smilelight  你好，你现在知道怎样进行预测吗？我也不知道怎么做
，哈哈哈

**Comment by smilelight** [comment]
你好，我之前看了你参考的[text_cnn pytorch实现](https://github.com/Shawn1993/cnn-text-classification-pytorch/blob/master/train.py)的代码，发现这里就是用于预测的代码：
```python
def predict(text, model, text_field, label_feild, cuda_flag):
    assert isinstance(text, str)
    model.eval()
    # text = text_field.tokenize(text)
    text = text_field.preprocess(text)
    text = [[text_field.vocab.stoi[x] for x in text]]
    x = torch.tensor(text)
    x = autograd.Variable(x)
    if cuda_flag:
        x = x.cuda()
    print(x)
    output = model(x)
    _, predicted = torch.max(output, 1)
    #return label_feild.vocab.itos[predicted.data[0][0]+1]
    return label_feild.vocab.itos[predicted.data[0]+1]
```

**Comment by Biaocsu** [comment]
谢谢

**Comment by smilelight** [comment]
@Biaocsu 您太客气了，我谢谢您才是呢

**Comment by Leanne-z** [comment]
@smilelight  请问预测函数解决了吗？我尝试写了一下，但在output = model(x)报错
    RuntimeError: Calculated padded input size per channel: (3 x 128). Kernel size: (4 x 128). Kernel size can't be greater than actual input size
这个大概是什么原因，
