### ISSUE TITLE
ValueError: Expected input batch_size (52) to match target batch_size (128).

### ISSUE THREAD

**Issue by chenjiefighting** [bigboNed3/chinese_text_cnn#11]
有人遇到这个问题吗？感谢
![捕获](https://user-images.githubusercontent.com/76989858/116807213-89170a80-ab64-11eb-9234-36c8d50f2348.PNG)

**Comment by Simon-LLong** [comment]
一样的问题，楼主咋解决的

> 有人遇到这个问题吗？感谢
> ![捕获](https://user-images.githubusercontent.com/76989858/116807213-89170a80-ab64-11eb-9234-36c8d50f2348.PNG)
