### ISSUE TITLE
from_pretrained函数

### ISSUE THREAD

**Issue by ShellingFord221** [bigboNed3/chinese_text_cnn#2]
你好，chinese_text_cnn/model.py中的第20行中的self.embedding.from_pretrained这个函数在哪里？好像没有找到定义的地方？

**Comment by practicingman** [comment]
> 你好，chinese_text_cnn/model.py中的第20行中的self.embedding.from_pretrained这个函数在哪里？好像没有找到定义的地方？

这个是Pytorch的函数
https://pytorch.org/docs/stable/nn.html#torch.nn.Embedding.from_pretrained
