### ISSUE TITLE
 feature.data.t_(), target.data.sub_(1)

### ISSUE THREAD

**Issue by AlexJakin** [bigboNed3/chinese_text_cnn#5]
Loading data...
The `device` argument should be set by using `torch.device` or passing a string
as an argument. This behavior will be deprecated soon and currently defaults to
cpu.
The `device` argument should be set by using `torch.device` or passing a string
as an argument. This behavior will be deprecated soon and currently defaults to
cpu.
Parameters:
        BATCH_SIZE=128
        CLASS_NUM=3
        CUDA=False
        DEVICE=-1
        DROPOUT=0.5
        EARLY_STOPPING=1000
        EMBEDDING_DIM=128
        EPOCHS=256
        FILTER_NUM=100
        FILTER_SIZES=[3, 4, 5]
        LOG_INTERVAL=1
        LR=0.001
        MAX_NORM=3.0
        MULTICHANNEL=False
        NON_STATIC=False
        PRETRAINED_NAME=sgns.zhihu.word
        PRETRAINED_PATH=pretrained
        SAVE_BEST=True
        SAVE_DIR=snapshot
        SNAPSHOT=None
        STATIC=False
        TEST_INTERVAL=100
        VOCABULARY_SIZE=35572
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    train.train(train_iter, dev_iter, text_cnn, args)
  File "d:\我的文档\桌面\workspace2\chinese_text_cnn\train.py", line 18, in trai
n
    feature.data.t_(), target.data.sub_(1)
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data o
r .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides /
storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap
 the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)

**Comment by AlexJakin** [comment]
能帮我看看这个是什么嘛 困恼很久了。。。。

**Comment by HughLK** [comment]
将这两句换成：
feature = feature.data.t()
target = target.data.sub(1)
